Repository AY2324S2-CS2103T-W08-3/tp, pull requests merged in 2024-04, with the labels that each got.

#88 Implement a command that clears the schedule list
  src/main/java/scm/address/logic/commands/ClearCommand.java
  src/main/java/scm/address/logic/commands/ClearScheduleCommand.java
  src/main/java/scm/address/logic/parser/AddressBookParser.java
  src/main/java/scm/address/model/Model.java
  src/main/java/scm/address/model/ModelManager.java
  src/test/java/scm/address/logic/commands/AddCommandTest.java
  src/test/java/scm/address/logic/commands/ClearScheduleCommandTest.java
  src/test/java/scm/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.Medium

#92 Update UG
  docs/UserGuide.md
Labels: type.Enhancement, type.Task, priority.Medium

#93 Update app window title and images
  docs/images/Ui.png
  docs/images/listImage.png
  docs/images/listSchedule.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Low

#95 Update messages
  src/main/java/scm/address/logic/Messages.java
  src/main/java/scm/address/logic/commands/EditScheduleCommand.java
  src/main/java/scm/address/logic/commands/FindAndExportCommand.java
  src/main/java/scm/address/logic/commands/FindCommand.java
  src/main/java/scm/address/logic/commands/FindScheduleCommand.java
  src/main/java/scm/address/logic/commands/ListCommand.java
  src/main/java/scm/address/logic/commands/ListScheduleCommand.java
  src/main/java/scm/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/scm/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/scm/address/model/person/TagsContainKeywordsPredicate.java
  src/main/java/scm/address/model/schedule/AfterDateTimePredicate.java
  src/main/java/scm/address/model/schedule/BeforeDateTimePredicate.java
  src/main/java/scm/address/model/schedule/DescriptionContainsKeywordsPredicate.java
  src/main/java/scm/address/model/schedule/DuringDateTimePredicate.java
  src/main/java/scm/address/model/schedule/TitleContainsKeywordsPredicate.java
  src/test/java/scm/address/logic/LogicManagerTest.java
  src/test/java/scm/address/logic/commands/FindCommandTest.java
  src/test/java/scm/address/logic/commands/FindScheduleCommandTest.java
  src/test/java/scm/address/logic/commands/ListCommandTest.java
  src/test/java/scm/address/logic/commands/ListScheduleCommandTest.java
Labels: type.Enhancement, priority.Low

#162 Fix some bugs for add schedule, calendar view and export
  docs/UserGuide.md
  src/main/java/scm/address/logic/commands/CalendarViewCommand.java
  src/main/java/scm/address/logic/commands/FindAndExportCommand.java
  src/main/java/scm/address/logic/parser/AddScheduleCommandParser.java
  src/test/java/scm/address/logic/parser/AddScheduleCommandParserTest.java
Labels: priority.Medium

#98 Update UML diagrams and developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task, priority.Medium

#164 Add changes to UG
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/listImage.png
  docs/images/listSchedule.png
Labels: priority.Medium

#165 Add changes to DG and diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Medium

#166 Add changes to DG
  docs/DeveloperGuide.md
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.Medium

#168 Fix theme bug
  src/main/java/scm/address/commons/core/GuiSettings.java
Labels: priority.Medium

#169 Update UG and images
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/lightTheme.png
Labels: priority.Medium
